### PR TITLE
fix name hiding

### PR DESCRIPTION
**Pull request by DanielaE**
Signed-off-by: Daniela Engert <dani@ngrt.de>

### CODE REVIEW

**Comment by DanielaE** [comment]
I have these changes in my take of Boost.Algorithm for more than one year now without any noticable negative effects in real-world projects.

**Comment by mclow** [comment]
I think I'd rather change the parameter names to `compute_bm_prefix` and `build_suffix_table` rather than the member variable names.

**Comment by DanielaE** [comment]
Well, I took the chance of upgrading my vc14.0 compiler from update 3 to the very latest post-upgrade 3 version that comes with the vc14.0 build tools in VS2017. The issue seems to be gone now and I drop this change from my take on Boost.

**Comment by mclow** [comment]
Ok; thanks for letting me know.  I will close this pull request.

**Pull request closed without merging**
