### PR TITLE
Enhance CI, add license and readme, and fix some issues

### LINKED ISSUE #52: Enable and enhance CI
Travis and Appveyor files were added 5 months ago, but CI was never enabled for this repository.
Add codecov.io, cppcheck, covscan, ubsan, and valgrind targets to improve quality.

### PR DESCRIPTION
**Pull request by jeking3**
This fixes #52 

Note the UBSAN job is expected to fail, it needs to be investigated and resolved.  I added symbol visibility to the exceptions but that didn't make a difference (it should be there anyway).

Since you do not have Travis CI or AppVeyor enabled on this repository, here are the build results:

AppVeyor: https://ci.appveyor.com/project/jeking3/algorithm/builds/20008102
Travis CI: https://travis-ci.org/jeking3/algorithm/builds/449921988

### CODE REVIEW

**Comment by jeking3** [comment]
@mclow a few things to do here:

1. Enable Travis CI builds on boostorg/algorithm
2. Enable AppVeyor builds on boostorg/algorithm
3. Analyze the UBSAN in the travis result link in the description.  It's a bad vtable in a dtor.

As admin for this repo you must do items 1 and 2 to enable PRs and merges into develop and master to run a build.

**Comment by jeking3** [comment]
Wow did you pay for travis-ci.com?

**Comment by jeking3** [comment]
This was passing on my fork...
https://github.com/jeking3/algorithm/pull/2

**Comment by jgopel** [comment]
What's the status on this? I think that landing a change along these lines would help me a lot, as I could offload most of my `b2` permutations to CI.

**Pull request merged**
