### PR TITLE
Apolukhin/constexpr

### PR DESCRIPTION
**Pull request by very-cool-name**

### CODE REVIEW

**Comment by apolukhin** [comment]
https://github.com/boostorg/range/pull/44 was merged to develop, so now it is safe to merge this pull request.

**Comment by ZaMaZaN4iK** [comment]
@mclow can you merge it, please? I can't see any broken changes.

**Comment by mclow** [comment]
Antony - I like all the constexpr stuff, but adding uses of `std::unary_function` (which has been removed in C++17) is not a direction that I want to go.  I'll play with that bit and suggest an alternative.

**Comment by ZaMaZaN4iK** [comment]
@mclow What is the status of the PR? Is it ready for merging into develop branch?

**Comment by mclow** [comment]
I'm not 100% sure that the constexpr tests are correct, but sure enough to merge.  Please ping me in a week or so to merge to master.

**Pull request merged**
