### PR TITLE
Create metadata file.

### PR DESCRIPTION
**Pull request by danieljames**
This file is currently used to automatically update the library list on the
website. It might also be used for other thing in the future. It's not
required, but it is helpful.

### CODE REVIEW

**Comment by pdimov** [comment]
Marshall, are you going to merge this, or shall I?

**Comment by mclow** [comment]
I added this manually in commit 0693c80c98402257817592e3ea23c96f2109a536, because the pull request had a mistake about the min/max maintainer.

**Comment by danieljames** [comment]
The maintainer field was taken from the libs/maintainers.txt file, so I updated it here: https://github.com/boostorg/boost/commit/34b0b0f0b434b24909cadd8ddc64b4381ba2c125

**Comment by mclow** [comment]
Bizarre. I could have sworn I did that back in August.

**Pull request closed without merging**
