### PR TITLE
use const_formatter insted of dissect_formatter  Ticket #10131

### PR DESCRIPTION
**Pull request by bogdanwilli**
reference to Ticket #10131

This may be a too naive solution to the problem I described in Ticket #10131, as I do not yet fully understand the concept behind the formatters.

This is my reasoning:

The trim_all___if() functions use the dissect_formatter with the first element as the argument. Since we are actually just trimming *all_ I doubt that it is necessary to keep the "head". Since I found the trim_fill_*_if() functions with an empty replacement string to work correctly, we could use the same approach here. I've replaced the dissect_formatter with the const_formatter taking an empty string argument. 

I have found this working with my code and examples. But as I said above, since I do not yet grasp the full concept of the formatters, there could be side effects I was not able to detect.

### CODE REVIEW

**Comment by ZaMaZaN4iK** [comment]
@mclow what is the current status of this PR?

**Comment by mclow** [comment]
this PR will never be merged - because it is against the master branch, not develop. However, there are a couple of things that I here might want to cherry-pick into the develop branch.

**Comment by ZaMaZaN4iK** [comment]
Did you cherry-pick things from the PR?

**Comment by mclow** [comment]
The docs and the `hex` change have been merged. The change to trim broke a bunch of tests, so I'm not going to merge that.

**Pull request closed without merging**
