### PR TITLE
Add find() variants.

### PR DESCRIPTION
**Pull request by tzlaine**

### CODE REVIEW

**Comment by tzlaine** [comment]
Lemme know if you want me to drop the .travis.yml bit.  If you like the idea of CI for Boost.Algorithm, I'll add an Appveyor script for MSVC support.

**Comment by mclow** [comment]
> `BidiIter find_backward(BidiIter first, BidiIter last, T const & x)`
East const, Zach?

I think I'd rather you proposed the CI stuff as a separate commit. That will keep the change log cleaner. I don't have a problem with the CI stuff, I'd just rather it was separated.

**Comment by tzlaine** [comment]
There, how's that?  I'll prepare an Appveyor script too before submitting the CI piece.

**Comment by mclow** [comment]
Thanks. Please watch the test bots; and ping me in a week or so to merge to master.

**Pull request merged**
