### PR TITLE
Add documentation to transform_inclusive_scan and transform_exclusive_scan

### PR DESCRIPTION
**Pull request by jgopel**

### CODE REVIEW

**Review by glenfe — CHANGES_REQUESTED** [review]
You also need to remove transform_inclusive_scan from https://github.com/boostorg/algorithm/blob/develop/doc/algorithm.qbk#L238 

i.e. The section named [Not-yet-documented C++17 Algorithms](https://www.boost.org/doc/libs/1_79_0/libs/algorithm/doc/html/algorithm/not_yet_documented_cxx17_algos.html)

Also, please lose the "sparkles" and other emoji in the commit messages.

**Comment by jgopel** [comment]
Hi @glenfe - Thanks for the feedback - I hadn't yet noticed the "Not-yet documented" section of that quickbook. Please let me know if there are any other changes I can make to help this land.

**Comment by glenfe** [comment]
Thanks @jgopel . This looks better now. To be complete, it should probably also add sections for the now documented functions in the `CXX17_inner_algorithms` documentation section.

i.e. In this block: https://github.com/boostorg/algorithm/blob/develop/doc/algorithm.qbk#L100-L109 we need something like:

```
[section:transform_inclusive_scan transform_inclusive_scan]
[*[^[link boost.algorithm.transform_inclusive_scan    transform_inclusive_scan]    ] ]
Transforms elements from the input range with an operation and then combines
those transformed elements with an operation such that the n-1th element and
the nth element are combined. Inclusivity means that the nth element is included
in the nth combination.
[endsect:transform_inclusive_scan]
```

And a similar section for  `transform_exclusive_scan`

**Comment by jgopel** [comment]
Done 🙂 Based on the existing entries in the quickbook, I kept the description a little shorter there and left the longer description for the linked page. If you'd prefer a different approach, just say the word!

**Review by glenfe — APPROVED** [review]
Looks good to me now - thanks.

**Pull request merged**
