### PR TITLE
fix narrowing conversions

### PR DESCRIPTION
**Pull request by DanielaE**
Signed-off-by: Daniela Engert <dani@ngrt.de>

### CODE REVIEW

**Comment by DanielaE** [comment]
I have these changes in my take of Boost.Algorithm for the last three years now without any noticable negative effects in real-world projects.

**Comment by ZaMaZaN4iK** [comment]
About your commit - Knuth-Morris-Pratt is wring. Difference type can be unsigned type. You can see line `j = -1` 
If we have unsigned type, it can broke algorithm.

**Comment by DanielaE** [comment]
Please let me comment on your objection:

- have a look at lines 99, 163, and 181. The skip vector's element type is `difference_type` and it's first element is initialized to -1 right before the loop which builds the skip vector. AFAICT the algorithm used here is the one described f.e. [here in Wikipedia](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm), which also requires a type which can hold a value of -1.

- there are other places in the implementation which silently assume `difference_type` to be a signed type (f.e. line 147).

- the documentation explicitly states that the iterator category of the algorithm's input arguments needs to be random access, which implies (by the standard, check the return type of `std::distance`) is a signed type.

So, IMHO, my fix to get rid of narrowing warnings in 64 bit code where `difference_type` is wider than `int` is sound.

Ciao, Dani

**Comment by ZaMaZaN4iK** [comment]
@DanielaE you are right. Sorry for annoying. Your fix is right.
@mclow Can you merge it?

**Pull request merged**
